# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field

class FTCompanydataItem(Item):
	symbol = Field()
	date = Field()
        ric = Field()
        issue_name = Field()
	Closing_price = Field()
        Open = Field()
        Day_high = Field()
        Day_low = Field()
        Previous_close = Field()
	Bid = Field()
	Offer = Field()
        Average_volume = Field()
        Shares_outstanding = Field()
        Free_float = Field()
        P_E_TTM = Field()
        Market_cap = Field()
        Market_cap_ccy = Field()
        EPS_TTM = Field()
        EPS_TTM_ccy = Field()
        Annual_div_TTM = Field()
        Annual_div_ccy = Field()
        Annual_div_yield = Field()
        Div_ex_date = Field()
        Div_pay_date = Field()
        Weeklowprice = Field()
        Weeklowdate = Field()
        Weekhighprice = Field()
        Weekhighdate = Field()
	bs_ccy = Field()
	years = Field()
	total_assets = Field()
	total_liabilities = Field()
	total_equity = Field()
	common_shares = Field()
	treasury_shares = Field()
	#csti = Field()
	#net_tr = Field()
	#ti = Field()
	#ppe = Field()
	#oca = Field()
	#tca = Field()
	#net_property = Field()
	#net_goodwill = Field()
	#net_intangibles = Field()
	#lti = Field()
	#long_term_notes_receivable = Field()
	#other_long_term_assets = Field()
	industry = Field()
	website = Field()
	total_revenue = Field()
	total_op_expense = Field()
	op_income = Field()
	EBT = Field()
	EAT = Field()
	Net_income = Field()
